### ISSUE TITLE
Support dogstatd with tags

### ISSUE THREAD

**Issue by killcity** [fabiolb/fabio#165]
Will Fabio eventually support (or does it already?) tagging statsd metrics? This is key when using Datadog.

**Comment by magiconair** [comment]
It may but I don't know. Someone else implemented the statsd support. Can you give an example ?

**Comment by killcity** [comment]
In it's simplest form:

https://help.datadoghq.com/hc/en-us/articles/206441345-Send-metrics-and-events-using-dogstatsd-and-the-shell

I also found a dogstatsd client written in Go.

https://github.com/ooyala/go-dogstatsd

Instead of having a bunch of metrics named explicitly per consul agent, we would have them sending with the same metric name and use tags to identify host, etc.

**Comment by magiconair** [comment]
Is that compatible with the standard statsd client?

**Comment by killcity** [comment]
I found one written by Datadog themselves. 

https://github.com/DataDog/datadog-go/tree/master/statsd <https://github.com/DataDog/datadog-go/tree/master/statsd>

I’m pretty certain this supports traditional statsd as well as extended tagging support for Dogstatsd users. I will confirm with Datadog.

**Comment by killcity** [comment]
To my chagrin, it doesn't support standard statsd. The datagram format is different.

http://docs.datadoghq.com/guides/dogstatsd/#datagram-format

I'm discussing some plausible solutions with a couple other engineers.

**Comment by magiconair** [comment]
If they are substantially different then we can just add it as another metric provider. If they were compatible then it could have made sense to just keep one of the two. You want to try a PR or want me to work on this?

**Comment by killcity** [comment]
The reporter you might be looking for? 

https://github.com/markchadwick/go-datadog

I'm a hack of a Go dev :) Perhaps if you have the cycles you can try? Thanks again for all the hard work on this project. Looking forward to pushing some serious traffic at a tier of Fabio LBs!

**Comment by magiconair** [comment]
ok, but then you'll have to wait a couple of days since I'm reworking the the parser for the configuration to support the path stripping that people seem to really want - besides other things.

**Comment by killcity** [comment]
That sounds fantastic. Thanks!

**Comment by aporcano** [comment]
Hey folks, is there any news on this functionality?

**Comment by magiconair** [comment]
Not yet. Just back from vacation and digging through the backlog.

**Comment by jippi** [comment]
Any love for this? :D

**Comment by magiconair** [comment]
I should have some time this week. I'll wrap up the other change I'm working on and then have a look. You're up for testing?

Frank Schröder

**Comment by jippi** [comment]
@magiconair Yep, I can test! :)

**Comment by killcity** [comment]
Same here

**Comment by magiconair** [comment]
Looks like there is an open issue on the go-metrics library to add tags support: https://github.com/rcrowley/go-metrics/issues/135 but that isn't going anywhere. 

We need to define an option to define the tags per route. What about `mtags=foo=1;bar` or `metricsTags=foo=1;bar`?

Since the `go-metrics` lib does not support tags natively at this point the best approach is to encode the tags in the key name (e.g. `key#tag1;tag2`) and then parse them out again before reporting the tags. That would require forking the statsd driver so that it understands the key format.

**Comment by magiconair** [comment]
Right now I am assuming that the tags are static per route. Is that a valid assumption?

**Comment by jippi** [comment]
I've written up a small statsd proxy that can convert fabio statsd path into tagged metrics; https://github.com/bownty/statsd-rewrite-proxy :)

**Comment by jippi** [comment]
@magiconair for me the tags would be per route, ala https://github.com/bownty/statsd-rewrite-proxy/blob/master/rules.go#L5-L7

**Comment by jippi** [comment]
tagged metrics is a bit tricky, since they also require the actual statsd path name to change, for it to make sense within UIs like datadog

**Comment by magiconair** [comment]
@jippi This is #207.

Can you explain your first statement a bit more? I'm not sure I get it. I thought I just add the `#tag1;tag2` to the statsd format and that's it.

**Comment by magiconair** [comment]
@jippi Created https://github.com/pubnub/go-metrics-statsd/pull/1 to fix #207

**Comment by magiconair** [comment]
@jippi and @killcity I've pushed a proof-of-concept into the branch which hopefully does what you want. You need to add `mtags=tag1;tag2` to your `urlprefix-/foo` definitions so that they look like `urlprefix-/foo mtags=tag1;tag2`. 

This is not the final code since I've hacked this into the pubnub/statsd implementation. I'd just like to check that I got the format right and that it does what it should do. Could you have a look please?

**Comment by jippi** [comment]
@magiconair for tagged metrics to be useful inside datadog UI, the path need to be "tag" less.

e.g. `fabio.http.status.{code}` make sense to emit as `fabio.http.response_code` 

then in the UI you can select `fabio.http.response_code` in the UI and group by the {code} (as its emitted as a named tag `code:200` example, and use these tags as facets.

So for me, tagged metrics is about a new path structure where the "value" from the normal statsd path is moved into named tags `code:200` or `service:example-service` - that structure works really really well inside datadog - datadog docs; http://docs.datadoghq.com/guides/metrics/#tags

**Comment by magiconair** [comment]
Got it. Thx

Frank Schröder

**Comment by killcity** [comment]
I think we would want to auto publish the following tags:

```service:
code:
urlprefix:```

**Comment by magiconair** [comment]
@killcity so you're also in favor of pushing the status code as a tag instead of the metric name just like @jippi suggested?

The main reason the change takes a bit longer is that the go-metrics library doesn't natively support tags which means that depending on the metrics backend fabio needs to report different metric names and put values into different places (e.g. service name, urlprefix, status code, ...)

I'm mulling over adding a full metrics abstraction layer which handles this or add a handful `if dogstatdMetrics` statements. Not so clean but much less work. I can do the nice refactor later.

**Comment by killcity** [comment]
Sorry for the long delay. Yes, I am also in favor of pushing the status code as a separate tag. Thanks for working on this one.

**Comment by magiconair** [comment]
Since 1.4 is out and the TCP proxy stuff is released I think I'll pick this one up again next together with the other metrics related issues #211, #253, #126

**Comment by magiconair** [comment]
Please see https://github.com/fabiolb/fabio/issues/211#issuecomment-375880738

**Comment by ketzacoatl** [comment]
@leprechau This is another metrics-related topic that would be good to review, as datadog is quite popular and the metrics integration is already possible via the existing statsd interface.
