### ISSUE TITLE
How to know what opts are supported in a route / consul tag?

### ISSUE THREAD

**Issue by jemc** [fabiolb/fabio#270]
I can see that I can specify `opts` in a urlprefix consul tag, as in `urlprefix-/ foo=1 bar=2`, but I can't find documented anywhere what opts are actually recognized by fabio as meaningful.

For example, let's say I want to set the `maxconn` that a service instance will accept to `100` in the tag, so that fabio directs at most 100 simultaneous connections to that service instance. I can't tell whether I should use `maxconn=100`, `proxy.maxconn=100`, or if this feature is even supported at all.

How can I know what opts are supported, or how to translate opts from the config file to be used in a consul tag?  Can this be added to the documentation somewhere?

**Comment by magiconair** [comment]
My bad. I need to update the docs more consistently. The opts from the config file are different than the opts on the routes. Right now the following opts are supported on a route:

```
strip=/foo         # strip '/foo' from the call to the upstream server
proto=tcp          # tcp upstream
proto=https        # https upstream
tlsskipverify=true # skip upstream tls verification
```

I'll update the docs.

**Comment by jemc** [comment]
Thanks for agreeing to update the docs; it's appreciated.

Is the per-instance `maxconn` feature something you would consider adding to fabio? [traefik currently supports this feature](https://docs.traefik.io/toml/#consul-catalog-backend).

Should I open a separate issue to discuss the `maxconn` feature?

**Comment by magiconair** [comment]
What do you need this for?

**Comment by jemc** [comment]
We have some Ruby-based web servers that use forking processes to handle requests (a la [unicorn](https://bogomips.org/unicorn/)), with each process handling one request at a time. Thus, the maximum number of simultaneous requests that each server can serve at a time is a fixed number (equal to the number of forked processes). Any additional requests that come in to the web server will be queued on listen socket.

However, these additional requests can be served more efficiently if they get queued at the *proxy* instead of the web server (because they can go to the next available web server in the entire pool, instead of getting stuck in an arbitrary round-robin-selected web server socket, which may happen to be serving very long-running requests). In HAProxy, we are currently using a per-server `maxconn` to achieve this behaviour. Since we are trying to replace our HAProxy + consul-template solution with fabio because of the traffic-interruption-during-reload issue, so we'd like to do something analogous with `maxconn` in fabio.

**Comment by magiconair** [comment]
How would this work for multiple fabio instances?

Frank Schröder

**Comment by jemc** [comment]
@magiconair - Sorry, I'm not sure I understand the implication of the question. Can you elaborate?

**Comment by magiconair** [comment]
If you have one service that can handle 10 connections and announces it through consul this is simple to keep track of if you have a single fabio instance. However, once you spin up the next one (for LB or HA purposes) then all fabios need to coordinate since the **service** can only handle 10 connections. So how would this work in if the number of fabio instances is dynamic, i.e. they can come and go?

**Comment by jemc** [comment]
Good question. We haven't had to deal with that issue because we use a static number of HAProxy servers that is known by our Chef recipe at the time when we deploy our HAProxy configuration template.

**Comment by magiconair** [comment]
I've updated the main README, the route config language docs on the wiki (https://github.com/fabiolb/fabio/wiki/Routing#config-language), the Quickstart on the Wiki (https://github.com/fabiolb/fabio/wiki/Quickstart) and the online documentation in fabio itself.

I'm going to merge this change and close this ticket since this the original question was about documentation and I don't want to morph tickets. I'll open another ticket for the `maxconn` question.
