### ISSUE TITLE
Q: does routing use first match or longest match of urlprefix-?

### ISSUE THREAD

**Issue by aalba6675** [fabiolb/fabio#310]
Does routing use first match or longest match?
I have two legacy services where one endpoint is a prefix of the other:

- svc1:  /animal/cat
- svc2: /animal 

By fluke clients of svc2 will never request for   /animal/cat/... will this work with urlprefix-/animal 
urlprefix-/animal/cat using longest match or first match?

**Comment by magiconair** [comment]
The search order is most to least specific. Registration order does not matter since this wouldn't be deterministic. Therefore, for `/animal/cat/white` you'll hit `svc2` but for `/animal/dog` you'll hit `svc1`

https://github.com/fabiolb/fabio/blob/master/route/table.go#L89-L92
https://github.com/fabiolb/fabio/blob/master/route/routes.go#L16-L19

**Comment by aalba6675** [comment]
Thanks !
