### ISSUE TITLE
Q: fabio memory usage is large, Why?

### ISSUE THREAD

**Issue by ultratxd** [fabiolb/fabio#312]
maxconn=5000
runtime.gogc=500

Soon it went up to 700m+, about one day

Is there any way to reduce it?

**Comment by magiconair** [comment]
The only thing we ever did to tune memory usage was to reduce `runtime.gogc` to have more collections. Smaller number (e.g. 100) usually equal more collections, higher numbers less collections. The default value is tuned for throughput of short-living connections. 

If you terminate TLS or have lots of long-running connections w/o timeout you may see increased memory usage. Also, there was a memory leak in the TCP proxy which was fixed in #321 but I don't know how big the impact was. This has been fixed in 1.5.2.

My suggestion is to run fabio with `GODEBUG= gctrace=1 ./fabio ...` and look at the output of the GC in the logs. Watch by how much the heap grows and whether the GC has an impact. Then slowly reduce the GOGC until this stabilizes.

**Comment by danielmotaleite** [comment]
` 6191 root       20   0 15.4G  9.9G  5352 S  3.2 15.8     0     0 26h34:23 /usr/local/bin/fabio -cfg /etc/fabio.conf`

10GB of ram! but i'm using 1.5.0, i will upgrade to 1.5.2 to see how much it will help

**Comment by magiconair** [comment]
@danielmotaleite the typical solution to this problem is to tune the `runtime.gogc` parameter to your use case. See the previous comment on how to address this. There was a memory leak in the TCP proxy which was addressed in #321 and is in 1.5.2. If you're using the TCP proxy then this might affect you.

**Comment by danielmotaleite** [comment]
After the upgrade and more that 24h later:
fabio    26033  4.8  0.1  96852 68932 ?        Ssl  Aug07  67:45 /usr/local/bin/fabio -cfg /etc/fabio.conf

much better... so yes, the memory leak in 1.5.x <1.5.2 was big, but it's now fixed!  :)

**Comment by favoretti** [comment]
We set gogc to 100 and memory remains relatively under control. That said, maybe the default of 800 is a bit too royal?

**Comment by magiconair** [comment]
The `800` value worked well for go1.4 and go1.5 for non-TLS connections and lots of short-lived requests. Might be time to run another test suite.
