### ISSUE TITLE
Allow comments in manual overrides

### ISSUE THREAD

**Issue by discobean** [fabiolb/fabio#379]
Some devs have been using overrides lately, and it would be good to ignore everything after a `#`.

This way somebody can include some documentation in each line for everybody else to see

**Comment by magiconair** [comment]
That should already work but needs to be at the start of the line. I can add that it also ignores comments at the end of the line. I thought I had documented this since this was for sure one of the first things I've implemented in the parser. We used that when selectively enabling override rules while switching services.

But there is no test for that and it isn't documented :(

https://github.com/fabiolb/fabio/blob/master/route/parse_new.go#L15
https://github.com/fabiolb/fabio/blob/master/route/parse_new.go#L71-L72

```
# this is a comment
// this is a comment as well
route add ...
```

**Comment by magiconair** [comment]
I've added a section to the docs just now:

https://github.com/fabiolb/fabio/wiki/Routing#comments

**Comment by discobean** [comment]
Hey, cool thank you :D
