### ISSUE TITLE
opts with host= with multiple routes does not work as expected

### ISSUE THREAD

**Issue by discobean** [fabiolb/fabio#385]
In Fabio 1.5.3 say I have 2 routes as such:

```
route add new-location-api location-api.domain.com/ http://localhost:9999 opts "host=new-location-api.domain.com"
route add old-location-api location-api.domain.com/ http://domain-location-api-production-external.dynamic.domain.com
```

The `host=xxxx` option appears on both routes.  (But notice the second route does not specify a host option)

If you put the second route above the first, then neither route has a `host=` option.

**Comment by magiconair** [comment]
Found it. The opts are stored on the target but set on the route. 

https://github.com/fabiolb/fabio/blob/4dbab1b7be568100164272aa661d797cd243d006/route/table.go#L156
https://github.com/fabiolb/fabio/blob/4dbab1b7be568100164272aa661d797cd243d006/route/table.go#L162

On my way to the airport now. I’ll see what I can do before the flight. Otherwise tomorrow.

**Comment by discobean** [comment]
All good mate, thanks

**Comment by magiconair** [comment]
@discobean I want to write an integration test for the `host` option but if you want then you can test the patch in #388 in the meantime.
