### ISSUE TITLE
Building master fails

### ISSUE THREAD

**Issue by phedoreanu** [fabiolb/fabio#482]
Building `master` fails with:
```
$ fabio(master) » make                                                                                                                          
[ -x "/Users/test/gocode/bin/govendor" ] || go get -u github.com/kardianos/govendor
govendor list +e | grep '^ e ' && { echo "Found missing packages. Please run 'govendor add +e'"; exit 1; } || : echo
 e  golang.org/x/text/internal/colltab
 e  golang.org/x/text/internal/language
 e  golang.org/x/text/internal/tag
 e  golang.org/x/text/language
 e  golang.org/x/text/transform
 e  golang.org/x/text/unicode/norm
Found missing packages. Please run 'govendor add +e'
make: *** [checkdeps] Error 1
```
Why aren't they checked into `vendor/`?

Have you thought switching from `govendor` to the **official** `dep`?

Please also read [PackageManagementTools](https://github.com/golang/go/wiki/PackageManagementTools).

> To see popularity of these tools, click [here](https://github.com/blindpirate/report-of-build-tools-for-java-and-golang#golang).

**Comment by leprechau** [comment]
The `dep` experiment is doomed to fail.  It was supposed to be part of the 1.10 official releases but it missed the mark.  In my opinion this was largely due to internal fighting and ivory tower perspectives that you can read in the project GitHub issue list.  I don't see that project overcoming those issues nor do I ever see it gaining widespread adoption.  Case in point there is already *another* vending tool being pushed `vgo` that according to the white paper is slated to replace `dep` that still hasn't been adopted.

**Comment by magiconair** [comment]
Building master does not fail. Tried this:

```
make ~/bla
export GOPATH=~/bla
go get github.com/fabiolb/fabio
find -type d ~/bla/src
```

**Comment by magiconair** [comment]
See #436 for why fabio won't switch to dep.
