### ISSUE TITLE
Question: resources (css, js files) by multiple sites

### ISSUE THREAD

**Issue by nerro** [fabiolb/fabio#717]
Hello,
I'm using Fabio as load balancer on my nomad cluster and have following issue, that my resources (css and js files) cannot be loaded correctly. This is how my 2 sites are configured:
1) `urlprefix-/my-first-site strip=/my-first-site`
2) `urlprefix-/my-second-site strip=/my-second-site`

I added `strip` because in html pages resources will be accessed i.e. `<link href="/main.css"..`

Question: is this a "right" approach? I checked documentation but didn't found an example with multiple sites behind fabio. I'm sure that the question is simple, but I don't get how to fix my issue :)

**Comment by pschultz** [comment]
If your sites refer to resources with absolute paths, rewriting the path will not work. That's true for any loadbalancer, not just fabio. Either 

- change your site to use relative paths (i.e. `main.css` instead of `/main.css`)
- or configure your site such that path rewriting is unnecessary (i.e. `http://<internal ip>/my-first-site` Just Works (tm)`)
- or use a dedicated (sub)domain for each site.

**Comment by nerro** [comment]
@pschultz, thanks for answer :). I'll try it.
