### ISSUE TITLE
docu fabio configure TLS/SSL(HTTPS) understanding problem

### ISSUE THREAD

**Issue by Sniphs98** [fabiolb/fabio#827]
Hey i have problems to understand the docu to configure TLS with consule

Example
cs=;type=consul;cert=http://localhost:8500/v1/kv/path/to/cert&token=123

i have two questions that i don't find an answer for.

is any name ?
wath is the token and where can i get it frome ?

**Comment by tristanmorgan** [comment]
I'll have a go at explaining this one.

because the type is consul and the path is inside the KV (key/value store) the certificates.

The names use the same scheme as the path type ones. `www.example.com.pem or www.example.com-{cert,key}.pem`

The token is from Consul (only needed if you have [ACL](https://www.consul.io/docs/security/acl)s enabled.)
