### ISSUE TITLE
This repository is unmaintaned.

### ISSUE THREAD

**Issue by Kamilcuk** [fabiolb/fabio#944]
Hi, this repository looks unmaintained.
Last commit is 2 years ago and there are several waiting pull requests.
That's fine.

Looking at [insights/network](https://github.com/fabiolb/fabio/network) I see some amazing work by many, many people, even lately by @aleksraiden and @jrcichra on their forks.

Would you be interested, and would it be possible to add maintainers to this repo, so people can contribute upstream and release new docker images?

I think fabio is a great and simple project and would be great for it to grow.
Thanks.

**Comment by aaronhurt** [comment]
Hi Kamicuk, thank you for the comments. This project is indeed in need of more attention. The current maintainers (mainly @nathanejohnson and myself) took over maintenance from the original author of the project back in 2020 (https://github.com/fabiolb/fabio/issues/735). At that time the company we both worked for actively used Fabio in production. Since then that company was acquired and absorbed.

We would absolutely welcome new maintainers to continue the project.

**Comment by tristanmorgan** [comment]
✋ 
I only really use Fabio on personal projects but willing to offer some time to keep updates and PRs moving.

**Comment by ketzacoatl** [comment]
@aaronhurt can we get @tristanmorgan access?

**Comment by aaronhurt** [comment]
I think that can be done! Thank you @tristanmorgan and @ketzacoatl let me make you contributors.

**Comment by tristanmorgan** [comment]
Thank you @aaronhurt

**Comment by nathanejohnson** [comment]
@tristanmorgan @ketzacoatl I know I've been awol from fabio for a while now, and some of that is due to me no longer working for ENA and not using fabio at the new place (we're all AWS), but also some of that is due to the fact that in my new job part of my duties is writing closed source proxies in go and I don't want to muddy the waters about who owns what IP.  That said, I've done the last several releases of fabio, and if you'd like any help from a high level on doing releases, please feel free to ping me and I'll assist in any way that I can.

Glad to see new faces as maintainers!

**Comment by ketzacoatl** [comment]
> I sent invites to you to join the maintainers group.

@aaronhurt, my apologies, I was too slow to get to the invite and accept it before it expired, can you resend? thank you :)

**Comment by aaronhurt** [comment]
> I think its time for a new point release. Can I ask @nathanejohnson or @aaronhurt please?

Yes, that  can be done. I'll have time this weekend to push a release.

**Comment by aaronhurt** [comment]
> > I sent invites to you to join the maintainers group.
> 
> @aaronhurt, my apologies, I was too slow to get to the invite and accept it before it expired, can you resend? thank you :)

Sorry, @ketzacoatl, I just noticed this. I re-sent the invite.

**Comment by aaronhurt** [comment]
@tristanmorgan @ketzacoatl what do you think about creating a small Slack group or something for better synchronous communication?

**Comment by tristanmorgan** [comment]
> @tristanmorgan @ketzacoatl what do you think about creating a small Slack group or something for better synchronous communication?

That sounds great.
